name: Code Quality Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    - name: Install dependencies
      run: poetry install --with dev
      
    - name: Run ruff linting
      run: poetry run ruff check .
      
    - name: Run ruff formatting check
      run: poetry run ruff format . --check